services:
  app-1:
    container_name: app-1
    image: alpine-app
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8081:8081
  
  app-2:
    container_name: app-2
    image: alpine-app
    tty: true
    ports:
      - 8082:8082
