
services:
  
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.101.0
    volumes:
      - ./otel-collector/config.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - otel_back_tier
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.45.5
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
        - --enable-feature=exemplar-storage
        - --config.file=/etc/prometheus/prometheus.yml
    volumes:
        - ./prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
    ports:
        - "9090:9090"
    networks:
      - otel_back_tier

  loki:
    container_name: loki
    image: grafana/loki:3.0.0
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1    
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - otel_back_tier
      
  tempo:
    container_name: tempo
    image: grafana/tempo:2.4.1
    command:
      - '--config.file=/configs/tempo.yaml'
      - '--auth.enabled=false'
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
    volumes:
      - ./tempo/config.yml:/configs/tempo.yaml:ro
      - ../../../../tempo-data/:/var/tempo/
    networks:
      - otel_back_tier
            
      
  grafana:
    container_name: grafana
    image: grafana/grafana:10.4.2
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - otel_back_tier

networks: 
  otel_back_tier: 
    name: otel_back_tier