# Grafana datasource's configuration file.
# See for more details: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
# Inspired by the following example:
# https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/grafana-datasources.yaml
apiVersion: 1

datasources:
#  - name: Mimir
#    type: prometheus
#    uid: prometheus
#    access: proxy
#    orgId: 1
#    url: http://mimir:9009/prometheus
#    basicAuth: false
#    isDefault: false
#    version: 1
#    editable: false

- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://host.docker.internal:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus

- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://host.docker.internal:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  jsonData:
    httpMethod: GET

- name: Loki
  type: loki
  uid: loki  
  access: proxy
  orgId: 1
  url: http://host.docker.internal:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true  
  jsonData:
    timeout: 60
    maxLines: 1000