# This OTEL collector configuration file with a single OTLP receiver for this purpose.

# Receivers' configuration section
# See for more details following documentation: https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      grpc:
      http:
#        endpoint: 4418
        endpoint: 0.0.0.0:4418

# Exporters' configuration section
# See for more details following documentation: https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  # Data sources: traces
  otlphttp/jaeger:
    endpoint: http://jaeger:4318

  otlphttp/tempo:
    endpoint: http://tempo:4318
    
  # Data sources: metrics
  prometheus:
#    endpoint: 9094
    endpoint: 0.0.0.0:9094
    namespace: hello_world_apps
    
  # Data sources: logging
  logging:
    loglevel: debug
  
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

# Services configuration section
# See for more details following documentation: https://opentelemetry.io/docs/collector/configuration/#services
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/jaeger, otlphttp/tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [loki,logging]