services:
  dbongo-1:
    container_name: dbongo-1
    image: mongo:6.0.13
    command: mongod --keyFile /keys/dbongo.key --bind_ip_all --replSet dbongo_rs
#    command: mongod --bind_ip_all --replSet dbongo_rs
    volumes:
      - ./data-files/data-1:/data/db
      - ./keys/dbongo.key:/keys/dbongo.key
    networks:
      dbongo-network:
        aliases:
          - dbongo-1.localhost
        ipv4_address: 172.20.0.2
    ports:
      - 27017:27017
    depends_on:
      - dbongo-2
    restart: always

  dbongo-2:
    container_name: dbongo-2
    image: mongo:6.0.13
    command: mongod --keyFile /keys/dbongo.key --bind_ip_all --replSet dbongo_rs
#    command: mongod --bind_ip_all --replSet dbongo_rs
    volumes:
      - ./data-files/data-2:/data/db
      - ./keys/dbongo.key:/keys/dbongo.key
    networks:
      dbongo-network:
        aliases:
          - dbongo-2.localhost
        ipv4_address: 172.20.0.3
    ports:
      - 27018:27017
    restart: always

  init-dbongo-replica-set:
    container_name: init-dbongo-replica-set
    image: mongo:6.0.13
    restart: no
    depends_on:
      - dbongo-1
      - dbongo-2
    command:
      - /bin/sh
      - -c 
      - | 
        sleep 5;
        mongosh --host host.docker.internal:27017 --eval '
            var db = (new Mongo("dbongo-1:27017")).getDB("test");    
            var config = { 
              "_id": "dbongo_rs",
              "version": 1,
              "members": [
                {
                  "_id": 1,
                  "host": "dbongo-1:27017",
                  "priority": 1,
                },
                {
                  "_id": 2,
                  "host": "dbongo-2:27017",
                  "priority": 2,
                }
             ]
            };
            rs.initiate(config, { force: true });
            //rs.initiate(config);
            rs.status();
          ';      
    networks:
      dbongo-network:

networks:
  dbongo-network:
    name: dbongo-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.254